### ISSUE TITLE
Print Function

### ISSUE THREAD

**Issue by 7h3v01c3** [norbusan/slick-google-map-plugin#12]
_Not wishing to double post_
Just thought I should follow your other suggestions in posting here.

Here is the shortcode associated with the Print Directions returing a 404 from google.

[google-map-v3 shortcodeid="cdc59ff70a" width="350" height="350" zoom="12" maptype="roadmap" mapalign="center" directionhint="false" language="default" poweredby="false" maptypecontrol="true" pancontrol="true" zoomcontrol="true" scalecontrol="true" streetviewcontrol="true" scrollwheelcontrol="false" draggable="true" tiltfourtyfive="false" enablegeolocationmarker="false" enablemarkerclustering="false" addmarkermashup="false" addmarkermashupbubble="false" addmarkerlist="132 Hawthorne Street, San Francisco, CA 94107{}1-default.png{}Automattic Inc." bubbleautopan="true" distanceunits="miles" showbike="false" showtraffic="false" showpanoramio="false"]

http://maps.google.com/maps?saddr=1600%20Amitheater%20parkway%20mountain%20view%20california&daddr=132%20Hawthorne%20Street,%20San%20Francisco,%20CA%2094107&dirflg=d&pw=2&doflg=ptm produces a 404

**Comment by norbusan** [comment]
Hmmm, again no problem with the very same shortcode. Added it to my blog, preview the post, select print in the browser and got a proper output pdf.

**Comment by 7h3v01c3** [comment]
Ok
Not sure why my output varies.
I have tried on two other sites with 4.4 Wp - these are on the same server
- So maybe something in my server configuration.

Ill keep looking.
