### ISSUE TITLE
HTML tag < a .... > appears when viewing the marker

### ISSUE THREAD

**Issue by Flobogo** [norbusan/slick-google-map-plugin#2]
When inserting a link in the tooltip, HTML < a .... > tag appears in the overview of the marker. (when viewing the marker by clicking)
It's not pretty! How to fix it?

**Comment by norbusan** [comment]
Hmm, I don't see what you mean. Can you please give an example? I tried to add a link to the description in the shortcode builder, which finally looked like:

```
[google-map-v3  ... addmarkerlist="石川県金沢市{}1-default.png{}Kenrokuen <a href=http://www.preining.info>at preining</a>" ... ]
```

which means that in the shortcode generator strange things are created. But when I view that page no "<a .." shows up.

How does your shortcode look like?

Thanks

**Comment by Flobogo** [comment]
Well, I had a link according to information from the documentation. When inserting the link, I didn't put HTML tag.
I followed the indication about Map Markers / Location, which asked to put a hashtag at the beginning and end of the link.
In fact, the bug occurs when flies over the marker with the mouse. (not when clicking)
Here are 3 screenshots to show the process and the result. 
![screenshot1_documentation_ map-markers_location_hyper-link](https://cloud.githubusercontent.com/assets/11201626/6391167/9a326e36-bdb3-11e4-9abb-211394d4b361.jpg)
![screenshot2_hashtag-start-and-end-link](https://cloud.githubusercontent.com/assets/11201626/6391170/a7fa83dc-bdb3-11e4-9edc-c577462babcf.jpg)
![screenshot3_bug-display-html-tag-link](https://cloud.githubusercontent.com/assets/11201626/6391172/b33a1672-bdb3-11e4-91e2-03d5ddc2b737.jpg)

Hope that can help.

**Comment by norbusan** [comment]
Sorry for the long silence, but I can still not reproduce this. I have created a post with the following shortcode

```
[google-map-v3 shortcodeid="TO_BE_GENERATED" width="350" height="350" zoom="12" maptype="roadmap" mapalign="center" directionhint="false" language="default" poweredby="false" maptypecontrol="true" pancontrol="true" zoomcontrol="true" scalecontrol="true" streetviewcontrol="true" scrollwheelcontrol="false" draggable="true" tiltfourtyfive="false" enablegeolocationmarker="false" enablemarkerclustering="false" addmarkermashup="false" addmarkermashupbubble="false" addmarkerlist="Place de la République, 71100 Chalon-sur-Saõne{}1-default.png{}Chalon, un ville animée #http://www.preining.info/ Voir la page consacrée à Chalon#" bubbleautopan="true" distanceunits="miles" showbike="false" showtraffic="false" showpanoramio="false"]
```

and it works without any problem, see the following screenshot:

![screenshot from 2015-11-27 14-57-43](https://cloud.githubusercontent.com/assets/1735589/11434901/45898dec-9517-11e5-83db-39d44572bd56.png)

Are you sure that there is something wrong, can you still reproduce it?

Thanks

Norbert

**Comment by Flobogo** [comment]
Hello,
I just tested again locally, and I can't reproduce the bug: everything works fine (even without having updated the plugin)
I'm sorry, there was perhaps a conflict with another plugin?
Thank you for having sought anyway.
Florence

**Comment by norbusan** [comment]
Thanks for re-checking. I am closing this issue now. If you find anything else, please let me know.

Norbert
