### ISSUE TITLE
How to turn off 

### ISSUE THREAD

**Issue by meulie** [norbusan/slick-google-map-plugin#6]
http://pub3.meulie.net/

This site is still in its building phase, but the widget-map illustrates the issue.
When you click on a marker, it shows a short excerpt of the text on the page, and 'Directions: To here - From here | Street View'.

How do I turn off 'Directions: To here - From here | Street View' on the widget-map?

**Comment by meulie** [comment]
fix

**Comment by norbusan** [comment]
No idea what was going on, but it seems to have been fixed by itself ;-) Thanks

**Comment by meulie** [comment]
no such luck, I'm afraid  ;)

I closed it because it's a duplicate of #7 , and this system doesn't let me delete #6 apparently.
