### ISSUE TITLE
How to turn off 'Directions: To here - From here | Street View' ?

### ISSUE THREAD

**Issue by meulie** [norbusan/slick-google-map-plugin#7]
http://pub3.meulie.net/

This site is still in its building phase, but the widget-map illustrates the issue.
When you click on a marker, it shows a short excerpt of the text on the page, and 'Directions: To here - From here | Street View'.

How do I turn off 'Directions: To here - From here | Street View' on the widget-map?

**Comment by norbusan** [comment]
If you want to disable it for all bubbles, that can be done easily by editing your css file (custom css or similar) and adding

```
.custom-bubble-links-section {
  display: none;
}
```

For single bubbles this is not possible at the moment.

Does this solve your problem?

All the best

Norbert

**Comment by meulie** [comment]
That resolves the issue indeed. Thanks!  :)

**Comment by norbusan** [comment]
Good to hear. Thanks for reporting back
