### ISSUE TITLE
Shortcode using KML file not showing place markers on front end

### ISSUE THREAD

**Issue by ovizii** [norbusan/slick-google-map-plugin#8]
I opened a ticket on WP dot org too but received no attention so I posted it here too.

So after your last advice on the WP dot org forums, I went and created a custom map on google maps, exported it to .kml and imported it to show it with a shortcode.

[google-map-v3 shortcodeid="7608c1c049" width="100%" height="450" zoom="14" maptype="roadmap" mapalign="center" directionhint="false" language="default" poweredby="false" maptypecontrol="true" pancontrol="true" zoomcontrol="true" scalecontrol="true" streetviewcontrol="true" scrollwheelcontrol="true" draggable="true" tiltfourtyfive="false" enablegeolocationmarker="false" enablemarkerclustering="false" addmarkermashup="false" addmarkermashupbubble="false" kml="http://pacura.ru/wp-content/uploads/2015/10/Southern-Peninsula-Drive.kml" bubbleautopan="true" distanceunits="km" showbike="false" showtraffic="true" showpanoramio="true"]

I don't have a live version but it works except it doesn't show any place markers, it only shows the route.

Any ideas? (Feel free to test the shortcode on your site, hotlinking shouldn't be a problem.)

**Comment by ovizii** [comment]
OK, the problem is not restricted to your plugin, I tried using another plugin to visualize the same KML file and no icons either.

I created the map via Google Maps => My Maps and selected default styles.

Any help please?

**Comment by norbusan** [comment]
I tried myself, too, to edit the map, but had the same effect. I guess that there is a limitation of what the maps API allows size wise, and you have several tracks that have many many points.

I honestly don't know. Sorry.

Since this is not a geniune problem of the current plugin, I thing I can close the issue.

**Comment by ovizii** [comment]
Just for the record, there are no more than 25 Location markers and the routes are between 10 of those. 

BUT I think the problem might be related to the fact that the location markers are pointing to Google's icons?

Have you been able to display a kml file generated from Google Maps with your plugin that shows place markers?
